---
abstract: 'All Acme::MetaSyntactic themes at once'
author:
  - 'Philippe Bruhat (BooK) <book@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-MetaSyntactic
requires:
  Acme::MetaSyntactic: 0
  Acme::MetaSyntactic::Themes: 0
  Acme::MetaSyntactic::Themes::Abigail: 0
  Acme::MetaSyntactic::buzzwords: 0
  Acme::MetaSyntactic::daleks: 0
  Acme::MetaSyntactic::dune: 0
  Acme::MetaSyntactic::errno: 0
  Acme::MetaSyntactic::legobatman: 0
  Acme::MetaSyntactic::legoharrypotter: 0
  Acme::MetaSyntactic::legoindianajones: 0
  Acme::MetaSyntactic::legolotr: 0
  Acme::MetaSyntactic::legopiratesofthecaribbean: 0
  Acme::MetaSyntactic::morning_musume: 0
  Acme::MetaSyntactic::nethack: 0
  Acme::MetaSyntactic::soviet: 0
  Acme::MetaSyntactic::vim: 0
  Acme::MetaSyntactic::xkcdcommon1949: 0
  strict: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Task-MetaSyntactic
  repository: http://github.com/book/Task-MetaSyntactic.git
version: 1.027
